dist: bionic

language: ruby

rvm: 
  - 2.6.5

services:
  - postgresql
  - xvfb

before_script:
  - psql -c 'create database "MareBnB-test";' -U postgres
  - bundle exec rake db:migrate RACK_ENV=test

script:
  - xvfb-run bundle exec rspec
  - bundle exec rubocop -c .rubocop.yml .
