dist: bionic

language: ruby

rvm: 
  - 2.6.5

services:
  - postgresql
  - xvfb

sudo: required

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin
  - psql -c 'create database "MareBnB-test";' -U postgres
  - bundle exec rake db:migrate RACK_ENV=test

script:
  - xvfb-run -a bundle exec rspec
  - bundle exec rubocop -c .rubocop.yml .
