development:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 4

production:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 4

test:
    adapter: postgresql
    encoding: unicode
    database: MareBnB-test
    pool: 4
