development:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 10

production:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 10

test:
    adapter: postgresql
    encoding: unicode
    database: MareBnB-test
    pool: 10
