development:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 2

production:
    adapter: postgresql
    encoding: unicode
    database: MareBnB
    pool: 2

test:
    adapter: postgresql
    encoding: unicode
    database: MareBnB-test
    pool: 2
